/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

#include <bootutil/sign_key.h>

/*
 * Even though this is in principle a Zephyr-specific file, the
 * simulator builds it and uses it as well. Because of that, we can't
 * use Kconfig symbols for key types, and have to rely on the MCUBoot
 * symbols (which Zephyr provides via this header, and the simulator
 * provides via the compiler command line).
 */
#include "mcuboot_config/mcuboot_config.h"

#if !defined(MCUBOOT_HW_KEY)
#if defined(MCUBOOT_SIGN_RSA) || defined(MCUBOOT_SIGN_EC256) ||                \
    defined(MCUBOOT_SIGN_ED25519)
#define HAVE_KEYS
#if defined(MCUBOOT_SIGN_RSA)
extern const unsigned char rsa_pub_key[];
extern unsigned int rsa_pub_key_len;
#elif defined(MCUBOOT_SIGN_EC256)
extern const unsigned char ecdsa_pub_key[];
extern unsigned int ecdsa_pub_key_len;
#elif defined(MCUBOOT_SIGN_ED25519)
extern const unsigned char ed25519_pub_key[];
extern unsigned int ed25519_pub_key_len;
#endif
#endif

#if defined(MCUBOOT_ENCRYPT_RSA) || defined(MCUBOOT_ENCRYPT_X25519) ||         \
    defined(MCUBOOT_ENCRYPT_EC256)

#define LENGTH_PRIVATE_KEY     (138)

unsigned char enc_priv_key[LENGTH_PRIVATE_KEY] = {
0x30, 0x81, 0x87, 0x02, 0x01, 0x00, 0x30, 0x13, 0x06, 0x07, 0x2A, 0x86,
0x48, 0xCE, 0x3D, 0x02, 0x01, 0x06, 0x08, 0x2A, 0x86, 0x48, 0xCE, 0x3D,
0x03, 0x01, 0x07, 0x04, 0x6D, 0x30, 0x6B, 0x02, 0x01, 0x01, 0x04, 0x20,
0xFE, 0xBC, 0x52, 0xCF, 0xCA, 0xC7, 0x1A, 0xEA, 0x87, 0x4A, 0xFF, 0x67,
0xFA, 0x47, 0xDE, 0xFA, 0x70, 0x0F, 0xC5, 0xBE, 0x23, 0x91, 0x74, 0xF0,
0xB8, 0x98, 0xEC, 0x21, 0x89, 0x15, 0xE6, 0x7D, 0xA1, 0x44, 0x03, 0x42,
0x00, 0x04, 0x0C, 0xC8, 0xDC, 0x62, 0x46, 0x8F, 0xE4, 0xE8, 0xC4, 0xE7,
0x16, 0x5D, 0x52, 0xC1, 0x73, 0x1F, 0xE5, 0x46, 0x9B, 0xB9, 0xBD, 0x69, 
0x0B, 0xF2, 0x12, 0x61, 0xCD, 0xE0, 0x2B, 0xA8, 0x29, 0xFD, 0x0D, 0x36,
0x4C, 0xA4, 0x50, 0x3B, 0x7C, 0x7C, 0x2F, 0xD5, 0x29, 0x5D, 0x6A, 0xBF,
0x9B, 0x9C, 0x24, 0x05, 0x8C, 0x92, 0x18, 0xC2, 0x95, 0x37, 0x95, 0x86,
0x71, 0x5E, 0xDF, 0xA4, 0x22, 0xB0
};
unsigned int enc_priv_key_len = LENGTH_PRIVATE_KEY;


#endif /* MCUBOOT_ENCRYPT_RSA || MCUBOOT_ENCRYPT_X25519 ||
         * MCUBOOT_ENCRYPT_EC256
         */

/*
 * NOTE: *_pub_key and *_pub_key_len are autogenerated based on the provided
 *       key file. If no key file was configured, the array and length must be
 *       provided and added to the build manually.
 */
#if defined(HAVE_KEYS)
const struct bootutil_key bootutil_keys[] = {
    {
#if defined(MCUBOOT_SIGN_RSA)
        .key = rsa_pub_key,
        .len = &rsa_pub_key_len,
#elif defined(MCUBOOT_SIGN_EC256)
        .key = ecdsa_pub_key,
        .len = &ecdsa_pub_key_len,
#elif defined(MCUBOOT_SIGN_ED25519)
        .key = ed25519_pub_key,
        .len = &ed25519_pub_key_len,
#endif
    },
};
const int bootutil_key_cnt = 1;
#endif /* HAVE_KEYS */
#else
unsigned int pub_key_len;
struct bootutil_key bootutil_keys[1] = {{
    .key = 0,
    .len = &pub_key_len,
}};
const int bootutil_key_cnt = 1;
#endif /* !MCUBOOT_HW_KEY */

#if defined(MCUBOOT_ENCRYPT_RSA) || defined(MCUBOOT_ENCRYPT_X25519) ||         \
    defined(MCUBOOT_ENCRYPT_EC256)
// unsigned char enc_priv_key[LENGTH_PRIVATE_KEY];
// static int enc_priv_key_len;
const struct bootutil_key bootutil_enc_key = {
    .key = enc_priv_key,
    .len = &enc_priv_key_len,
};
#elif defined(MCUBOOT_ENCRYPT_KW)
#error "Encrypted images with AES-KW is not implemented yet."
#endif
