/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

#include <bootutil/sign_key.h>

/*
 * Even though this is in principle a Zephyr-specific file, the
 * simulator builds it and uses it as well. Because of that, we can't
 * use Kconfig symbols for key types, and have to rely on the MCUBoot
 * symbols (which Zephyr provides via this header, and the simulator
 * provides via the compiler command line).
 */
#include "mcuboot_config/mcuboot_config.h"

#if !defined(MCUBOOT_HW_KEY)
#if defined(MCUBOOT_SIGN_RSA) || defined(MCUBOOT_SIGN_EC256) ||                \
    defined(MCUBOOT_SIGN_ED25519)
#define HAVE_KEYS
#if defined(MCUBOOT_SIGN_RSA)
extern const unsigned char rsa_pub_key[];
extern unsigned int rsa_pub_key_len;
#elif defined(MCUBOOT_SIGN_EC256)
extern const unsigned char ecdsa_pub_key[];
extern unsigned int ecdsa_pub_key_len;
#elif defined(MCUBOOT_SIGN_ED25519)
extern const unsigned char ed25519_pub_key[];
extern unsigned int ed25519_pub_key_len;
#endif
#endif

#if defined(MCUBOOT_ENCRYPT_RSA) || defined(MCUBOOT_ENCRYPT_X25519) ||         \
    defined(MCUBOOT_ENCRYPT_EC256)

#define LENGTH_PRIVATE_KEY     (138)

unsigned char enc_priv_key[LENGTH_PRIVATE_KEY] =
    {
        0x30, 0x81, 0x87, 0x2,  0x1,  0x0,  0x30, 0x13, 0x6,  0x7,  0x2A, 0x86,
        0x48, 0xCE, 0x3D, 0x2,  0x1,  0x6,  0x8,  0x2A, 0x86, 0x48, 0xCE, 0x3D,
        0x3,  0x1,  0x7,  0x4,  0x6D, 0x30, 0x6B, 0x2,  0x1,  0x1,  0x4,  0x20,
        0x1B, 0xD3, 0xC2, 0xE3, 0x82, 0x8E, 0xAF, 0x12, 0x45, 0x73, 0x5,  0xB7,
        0x8B, 0x64, 0x2C, 0x51, 0x73, 0x2F, 0xD9, 0xFB, 0xED, 0xC4, 0x8E, 0x4E,
        0x6,  0x23, 0xA3, 0xF0, 0x31, 0x57, 0x4F, 0xE0, 0xA1, 0x44, 0x3,  0x42,
        0x0,  0x4,  0xF4, 0x53, 0x51, 0x6,  0xDB, 0x7,  0x6F, 0xAD, 0x81, 0xFC,
        0xC1, 0xE8, 0xB7, 0x19, 0xF,  0x63, 0x16, 0x77, 0xBA, 0xBD, 0x5D, 0x11,
        0x2A, 0x38, 0x68, 0xEF, 0x39, 0x9F, 0x10, 0xA6, 0x46, 0xE6, 0xE3, 0x59,
        0xC6, 0xE1, 0xA,  0x6C, 0x80, 0x9E, 0x37, 0xC5, 0x3D, 0xC,  0x47, 0xFE,
        0x31, 0xEE, 0x92, 0xF9, 0x54, 0x83, 0xA3, 0x51, 0xF7, 0xD1, 0xCC, 0x10,
        0xEF, 0x26, 0xD8, 0x87, 0x92, 0xA5
    };

unsigned int enc_priv_key_len = LENGTH_PRIVATE_KEY;

#endif /* MCUBOOT_ENCRYPT_RSA || MCUBOOT_ENCRYPT_X25519 ||
         * MCUBOOT_ENCRYPT_EC256
         */

/*
 * NOTE: *_pub_key and *_pub_key_len are autogenerated based on the provided
 *       key file. If no key file was configured, the array and length must be
 *       provided and added to the build manually.
 */
#if defined(HAVE_KEYS)
const struct bootutil_key bootutil_keys[] = {
    {
#if defined(MCUBOOT_SIGN_RSA)
        .key = rsa_pub_key,
        .len = &rsa_pub_key_len,
#elif defined(MCUBOOT_SIGN_EC256)
        .key = ecdsa_pub_key,
        .len = &ecdsa_pub_key_len,
#elif defined(MCUBOOT_SIGN_ED25519)
        .key = ed25519_pub_key,
        .len = &ed25519_pub_key_len,
#endif
    },
};
const int bootutil_key_cnt = 1;
#endif /* HAVE_KEYS */
#else
unsigned int pub_key_len;
struct bootutil_key bootutil_keys[1] = {{
    .key = 0,
    .len = &pub_key_len,
}};
const int bootutil_key_cnt = 1;
#endif /* !MCUBOOT_HW_KEY */

#if defined(MCUBOOT_ENCRYPT_RSA) || defined(MCUBOOT_ENCRYPT_X25519) ||         \
    defined(MCUBOOT_ENCRYPT_EC256)
// unsigned char enc_priv_key[LENGTH_PRIVATE_KEY];
// static int enc_priv_key_len;
const struct bootutil_key bootutil_enc_key = {
    .key = enc_priv_key,
    .len = &enc_priv_key_len,
};
#elif defined(MCUBOOT_ENCRYPT_KW)
#error "Encrypted images with AES-KW is not implemented yet."
#endif
